### ISSUE TITLE
(BAN-B608) Risk of possible SQL injection vector through string-based query construction

### ISSUE THREAD

**Issue by V3ntus** [darvester/darvester#24]
## Description
An SQL injection attack consists of insertion or “injection” of a SQL query via the input data given to an application. It is a very common attack vector. Unless care is taken to sanitize and control the input data when building such SQL statement strings, an injection attack becomes possible.

## Occurrences
There are 8 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/V3ntus/darvester/issue/BAN-B608/occurrences/](https://deepsource.io/gh/V3ntus/darvester/issue/BAN-B608/occurrences/)

**Comment by Coder-Manan** [comment]
The link is giving a 404 error, please check it

**Comment by V3ntus** [comment]
@Coder-Manan Deepsource has been deactivated for the time being
