### ISSUE TITLE
[GEN2] Enhance user experience in mobile devices

### ISSUE THREAD

**Issue by MaguiRocha** [darvester/darvester#53]
**Describe the bug**
When trying to test the page on small screens I get a general error in the content

**To Reproduce**
1. Go to 'http://darvester.gladiusso.com/'
2. Click on 'dev tools'
3. slide the bar

**Expected behavior**

**Screenshots**
![Captura de pantalla 2022-10-05 164824](https://user-images.githubusercontent.com/111162805/194149712-27559f08-bee0-42d1-a412-984e6e8a54a7.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [e.g. chrome]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by V3ntus** [comment]
Thanks for opening an issue! This has definitely been a priority since the start. I have been prioritizing core functions first as I've been the only developer since, although I welcome anyone to improve the styling.

**Comment by V3ntus** [comment]
Done! @MaguiRocha

**Comment by MaguiRocha** [comment]
I'm sorry, but I couldn't solve the problem, please unassign me
again, sorry! 😭

**Comment by V3ntus** [comment]
No worries! I appreciate you showing interest in the project nonetheless :)

**Comment by MaguiRocha** [comment]
Thank you very much!
I look forward to contributing next year! ✨

**Comment by V3ntus** [comment]
Closing as node.js builds of gen2 may be sunsetting in favor for the gen2-flutter branch.
