### ISSUE TITLE
Under Tracks, visit Github links are not working

### ISSUE THREAD

**Issue by muskanbararia** [darvester/darvester#54]
**Describe the bug**
Under Tracks, visit Github links are not working

**To Reproduce**
1. Go to tracks card
2. Click on Visit Github

**Expected behavior**
Should redirect to corresponding link

**Screenshots**

**Desktop (please complete the following information):**
 - OS: WIndows
 - Browser Brave
 - Version 1.44

**Comment by muskanbararia** [comment]
Would love to work on this under hacktoberfest

**Comment by V3ntus** [comment]
Hey @muskanbararia thanks for opening an issue! Could you elaborate on where to find the Tracks and if this is a `gen2` branch issue?
