### ISSUE TITLE
I will improve you redme.md file 

### ISSUE THREAD

**Issue by BxtGeek** [darvester/darvester#55]
**Is your feature request related to a problem? Please describe.**
I will improve you redme.md file 

**Describe the solution you'd like**
More clear redme.md file. help users to understand the project better

**Describe alternatives you've considered**
By adding the design element and emoji

**Additional context**
NA

**Comment by V3ntus** [comment]
Hey @BxtGeek thanks for opening an issue. I agree, the readme.md definitely needs sprucing up. Submit a PR and I'll be happy to look over it, thanks!

**Comment by BxtGeek** [comment]
Hello @V3ntus  while PR getting the below error. Please help.
![image](https://user-images.githubusercontent.com/25264755/194698832-2a17cd26-0d54-4085-96d8-fd8656e0b25e.png)

**Comment by V3ntus** [comment]
Don't worry, it's just requiring my review. I'll take a look at it

**Comment by BxtGeek** [comment]
okay
