### ISSUE TITLE
[Enhancement] Scrape member trough Preview functionality

### ISSUE THREAD

**Issue by contusionglory** [darvester/darvester#62]
Enable scraping trough the "Explore Public Servers" tab, when clicked on a server there is a preview of the server and the members list is still visible so it can be scraped without risking to much for multiple server joins. Maybe it can automatically scrape all server with a specific keyword
![Explore Public Servers button](https://user-images.githubusercontent.com/102427829/202872837-bfb1fa16-2696-4977-9237-57480d6682d4.png)
![Searching feature](https://user-images.githubusercontent.com/102427829/202872854-7128918c-c318-42fc-8720-196ef9fa8142.png)
![Multiple page](https://user-images.githubusercontent.com/102427829/202872857-2c6fa163-b7cf-4be2-ac66-d635fb98a734.png)
![Preview server](https://user-images.githubusercontent.com/102427829/202872859-447c5c8b-c67f-45e2-86bc-a0ba7d191217.png)

**Comment by V3ntus** [comment]
Thanks for opening an issue! Staying away from browser automation like Selenium, it would be nice if there was a public API endpoint to grab the list of servers. I suppose it's time to catch up on the API docs

**Comment by contusionglory** [comment]
I found out some information looking at the requests made
The guild that are shown when you click the "Explore Public Server" buttons:
https://ouwou.github.io/discord-undocumented/guild_discovery

For searching trough the guild there is a POST request on 
https://nktzz4aizu-dsn.algolia.net/1/indexes/prod_discoverable_guilds/query
and with json data 
```json
{"query":"game","filters":"auto_removed:false AND approximate_presence_count> 0 AND approximate_member_count>200 AND (primary_category_id=5 OR categories.id=5)","optionalFilters":["preferred_locale: en-US"],"length":100,"offset":0,"restrictSearchableAttributes":["name","description","keywords","categories.name","categories.name_localizations.en-US","primary_category.name","primary_category.name_localizations.en-US","vanity_url_code"]}
```
the query is what you want to check and you can edit the lenght to 1000 to get all the servers that it can fetch
and has this headers

```html
POST /1/indexes/prod_discoverable_guilds/query?x-algolia-agent=Algolia%20for%20JavaScript%20(4.1.0)%3B%20Browser HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 437
Host: nktzz4aizu-dsn.algolia.net
Origin: https://discord.com
Pragma: no-cache
Referer: https://discord.com/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36
content-type: application/x-www-form-urlencoded
sec-ch-ua: "Chromium";v="103", ".Not/A)Brand";v="99"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
x-algolia-api-key: aca0d7082e4e63af5ba5917d5e96bed0
x-algolia-application-id: NKTZZ4AIZU
```

For the guild preview there is this documentation
https://ouwou.github.io/discord-undocumented/guild_lurking

**Comment by V3ntus** [comment]
Is this query taken from the Discord client? Due to XSS/CSRF concerns, I'd like to verify that before implementing an API request to a different domain

**Comment by contusionglory** [comment]
Yes is taken directly from the network tab when i'm searching something in
the explore public server on discord web

**Comment by contusionglory** [comment]
Yes is taken directly from the network tab when I'm searching something in
the explore public server on discord web

**Comment by V3ntus** [comment]
> `/discoverable-guilds?offset=0&limit=30`

Originating from an endpoint within the Discord domain: ![image](https://user-images.githubusercontent.com/29584664/202909277-2ff10738-fd15-4282-8fbe-6e9cd3aef670.png)

Through this endpoint, we get a few important things, such as the Guild ID and the `vanity_url_code` which we can use to "lurk" the server and ultimately harvest.

**Comment by V3ntus** [comment]
This is definitely a great feature we can implement, automating the guild join process to eliminate manual labor in favor of automation.

**Comment by contusionglory** [comment]
```python
import requests
import json

url = "https://nktzz4aizu-dsn.algolia.net/1/indexes/prod_discoverable_guilds/query"
query=input("Search query:")
length=int(input("How many server to retrieve[Max. 1000]:"))

payload = {
    "query": query,
    "filters": "auto_removed:false AND approximate_presence_count> 0 AND approximate_member_count>200 AND (primary_category_id=5 OR categories.id=5)", #primary category number can be change for different result(categories.id = 5 is Science & Tech) or [ AND (primary_category_id=5 OR categories.id=5)] can be remove to get all result
    "optionalFilters": ["preferred_locale: en-US"], #can be change in different languages
    "length": length,
    "offset": 0, #can be set to a max of 2000(max server that can be retrieved 3000)
    "restrictSearchableAttributes": ["name", "description", "keywords", "categories.name", "categories.name_localizations.en-US", "primary_category.name", "primary_category.name_localizations.en-US", "vanity_url_code"]
}
headers = {
    "Accept": "*/*",
    "Accept-Language": "en-US,en;q=0.9",
    "Cache-Control": "no-cache",
    "Connection": "keep-alive",
    "Origin": "https://discord.com",
    "Pragma": "no-cache",
    "Referer": "https://discord.com/",
    "Sec-Fetch-Dest": "empty",
    "Sec-Fetch-Mode": "cors",
    "Sec-Fetch-Site": "cross-site",
    "content-type": "application/json",
    "x-algolia-api-key": "aca0d7082e4e63af5ba5917d5e96bed0",
    "x-algolia-application-id": "NKTZZ4AIZU"
}

response = json.loads(requests.request("POST", url, json=payload, headers=headers).text)

for server in response['hits']:
    print(server['id'],server['vanity_url_code']) #vanity_url_code can be none
```
I created a small program to leverage the search function and retrieve all server id and vanity_url_code if exists
Hope this can help

**Comment by V3ntus** [comment]
Thank you @contusionglory

**Comment by V3ntus** [comment]
A commit (ca42ea8d04c0162635f525eb7686a50180b5c2f9) was pushed to include this feature. Closing as completed
